### ISSUE TITLE
The time measuring module in run_script_dgl.py is not accurate

### ISSUE THREAD

**Issue by yzh119** [GustikS/GNNwLRNNs#1]
Dear authors,

Recently I went through your paper [Lossless Compression of Structured Convolutional Models via Lifting](https://arxiv.org/pdf/2007.06567.pdf) and found it very interesting.

However, I noticed that you did not correctly measure the DGL running time on GPU, and most of the DGL time you measured comes from the graph conversion overhead (the DGLGraph is converted from pyg format).

The following code section
https://github.com/GustikS/GNNwLRNNs/blob/0a628775be7f2639a6e00703470f35e7fe74483e/run_script_dgl.py#L305-L319
will not correctly record the real GPU execution time because in PyTorch the GPU operators are asynchronous. To get the accuracy GPU time, you can either put `torch.cuda.synchronize()` after and before your `time.time()` statement or use `torch.cuda.Event` for more accurate profiling. (See https://pytorch.org/docs/stable/notes/cuda.html). 

The graph conversion overhead could be hidden by enabling multi-processing data loader, I could help implement this if needed.

I know the DGL implementation only acts as a baseline in your paper but I think a fair comparison looks better :)
btw, in the DGL 0.5 release (coming soon) we greatly improved the speed performance, please stay tuned if you're interested.

Best,
Zihao

**Comment by GustikS** [comment]
Dear Zihao,

thanks a lot your insights, I surely want to get it right and fair! I have just a very basic experience with the framework, so your help is most welcome.

Actually, all of the comparative experiments in the papers are run on CPU, as it was faster (for all the frameworks) than GPU in the given setting (lots of small sparse graphs, no batching...I suspect that that probably helps PyG over DGL, too? The only exception are the mini-batching experiments with PyG from another paper - fig. 7 in https://arxiv.org/abs/2007.06286). Nevertheless I'm interested in aligning it properly on the GPU, too.

I've just tried playing with the `torch.cuda.synchronize()` but did not find any difference (I believe it is synchronized implicitly as I read/print the outputs to console, so all the GPU operations need to terminate anyway, no?).

But I do not get your remark on the graph conversion overhead - do you mean the `convert_to_dgl` fcn? The DGLGraph objects are created during data loading, in advance to the time measurements. Or is there some extra overhead during the sending to GPU that makes it unfair w.r.t. doing the same with the PyG's Data object? Maybe I misunderstood something there.

> btw, in the DGL 0.5 release (coming soon) we greatly improved the speed performance, please stay tuned if you're interested.

Yeah, I'm happy to try it again with the new version (of both the frameworks).

Thank you very much,
Gustav

**Comment by yzh119** [comment]
Hi Gustav,

Sorry I did not notice that you are evaluating on CPU, in this case, `torch.cuda.synchronize()` does not matter actually. Yes I mean the `convert_to_dgl` function, if you are measuring the GPU time without synchronizing then the graph conversion time would be recorded because of the asynchronous execution of PyTorch operators. But anyways you are not working on GPU.

Would you mind me coming back here posting some new speed results after the release of DGL 0.5 (where we removed some python-end overheads and accelerated several kernels)?

**Comment by GustikS** [comment]
Hi Zihao,

yes I get that it's asynchronous (I hope), but what I meant is
1. the `convert_to_dgl` is called only once and before the actual time measurements (as you can check)
1. I've tried to add the synchronization in various places and did not observe any differences (even on GPU, probably for the reasons stated above)

Yes, let me know! I can set a reminder to try again with the new version. Or pull request or anything. I'm curious about both the PyG and DGL libraries, although my focus is mostly on expressivness of the models, not speed of the libraries (this comparison was mostly coincidental).

Thank you,
Gustav
